import fs from 'fs';
import path from 'path';
import nodemailer from 'nodemailer';
import verifyToken from '../../../middleware/verifyToken';

function runMiddleware(req, res, fn) {
  return new Promise((resolve, reject) => {
    fn(req, res, (result) => {
      if (result instanceof Error) return reject(result);
      return resolve(result);
    });
  });
}

const createTransporter = () => {
  const host = process.env.SMTP_HOST;
  const port = Number(process.env.SMTP_PORT || 587);
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  return nodemailer.createTransport({ host, port, auth: { user, pass } });
};

async function sendWithRetry(mailOptions, retries = 3) {
  const transporter = createTransporter();
  for (let attempt = 1; attempt <= retries; attempt += 1) {
    try {
      await transporter.sendMail(mailOptions);
      return true;
    } catch (error) {
      if (attempt === retries) throw error;
    }
  }
  return false;
}

/**
 * @param {import('next').NextApiRequest} req
 * @param {import('next').NextApiResponse} res
 */
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, message: 'Method not allowed' });
  }

  try {
    await runMiddleware(req, res, verifyToken);
  } catch (err) {
    return;
  }

  const { reportUrl, recipients, subject } = req.body || {};
  if (!reportUrl || !Array.isArray(recipients) || recipients.length === 0) {
    return res.status(400).json({ success: false, message: 'Invalid payload' });
  }

  try {
    const filePath = path.join(process.cwd(), 'public', reportUrl.startsWith('/') ? reportUrl.slice(1) : reportUrl);
    if (!fs.existsSync(filePath)) {
      return res.status(400).json({ success: false, message: 'Report file not found' });
    }

    const mailOptions = {
      from: process.env.SMTP_USER,
      to: recipients,
      subject: subject || 'EpochEye Automated Report',
      text: 'Please find attached the automated report generated by EpochEye.',
      attachments: [
        {
          filename: path.basename(filePath),
          path: filePath,
        },
      ],
    };

    await sendWithRetry(mailOptions, 3);
    return res.status(200).json({ success: true, message: `Report emailed to ${recipients.length} recipients` });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Email sending failed', error: error?.message });
  }
}
